version: "3.4"

services:

  postgresql:
    container_name: db
    image: "docker.io/library/postgres:16-alpine"
    restart: unless-stopped
    volumes: 
      - '/data/findtheti-me/postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-findthetime}
      POSTGRES_DB: ${PG_DB:-findthetime}

  findthetime:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://${PG_USER:-findthetime}:${PG_PASS}@db/${PG_DB:-findthetime}"
      SSL_ENABLED: 'true' # when this is set to false ( default ), the ssl port is not listened to.
      SSL_REDIRECT: 'true'
      SSL_PORT: '8443'
      SSL_CERT_PATH: '/etc/findtheti-me/certs/server.cert'
      SSL_KEY_PATH: '/etc/findtheti-me/certs/server.key'
    volumes:
      - '/home/haedhutner/Workspace/findtheti-me/.self-signed:/etc/findtheti-me/certs' 
    ports:
      - '8080:8080'
      - '8443:8443'