services:

  postgresql:
    container_name: db
    image: "docker.io/library/postgres:16-alpine"
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER:-findthetime}
      POSTGRES_DB: ${PG_DB:-findthetime}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 10s
    ports:
      - '5432:5432'

  findthetime:
    depends_on:
      postgresql:
        condition: service_healthy
    build: 
      dockerfile: ./Dockerfile
    environment:
      GIN_MODE: debug
      FTT_API_DB_URL: "postgres://${PG_USER:-findthetime}:${PG_PASS}@postgresql:5432/${PG_DB:-findthetime}?sslmode=disable"
    ports:
      - '8080:8000'